global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: mirr-server
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['mirr-web-server:8080']

  - job_name: node-exporter
    metrics_path: '/metrics'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: mysql-exporter
    metrics_path: /metrics
    static_configs:
      - targets: ['mysql-exporter:9104']